= Transition Extraction, Training and Execution Harness for flipR
Nils Hoffmann <nils.hoffmann@isas.de>
:toc: macro

// image:https://travis-ci.org/lifs-tools/jmzTab-m.svg?branch=master["Build Status", link="https://travis-ci.org/lifs-tools/jmzTab-m"] image:https://img.shields.io/maven-central/v/de.isas.mztab/jmztabm-cli.svg["Maven Central", link="https://search.maven.org/search?q=a:jmztabm-cli"] image:https://img.shields.io/github/release/lifs-tools/jmzTab-m.svg["Latest Release", link="https://github.com/lifs-tools/jmzTab-m/releases/latest"] image:https://zenodo.org/badge/107954666.svg["DOI", link="https://zenodo.org/badge/latestdoi/107954666"] image:https://img.shields.io/docker/pulls/lifs/jmztabm-cli.svg["Docker Hub Pulls", link="https://hub.docker.com/r/lifs/jmztabm-cli"] image:https://anaconda.org/bioconda/jmztab-m/badges/installer/conda.svg["Install with Conda", link="https://anaconda.org/bioconda/jmztab-m"]

This project provides an execution harness including transition extraction from mzML files, automatic model training and selection based on the https://github.com/lifs-tools/flipr[flipr project].

To use it on Linux systems with parallelized training, please see the https://github.com/lifs-tools/flipr[flipr-trainer].

flipR (Fragment-based Lipid Intensity Prediction) predicts MS-platform specific lipid fragment profiles that simplify the selection of optimized collision energies for custom lipid transition libraries with https://github.com/lifs-tools/LipidCreator[LipidCreator] in conjunction with https://skyline.ms/project/home/software/Skyline/begin.view[Skyline].

The Maven site with JavaDoc is available https://lifs-tools.github.io/flipr-transition-extractor[here].

toc::[]

== Building the project and generating client code from the command-line

In order to build the client code and run the unit tests, execute the following command from a terminal:

	./mvnw install

This generates the executable JAR file for reading and mapping of transition lists, mapping files and mzML transition extraction.

The generated JAVA code is available in a jar archive below the `target` directory:

. flipr-transition-extractor-<VERSION>.jar

== Running the application

If you want to run the application from the command line, change to the `target` folder after building the project.
Then enter the following command:

	java -jar flipr-transition-extractor-1.0.9.jar

This will print all possible arguments for the transition extractor. 

NOTE: You need to have the https://github.com/lifs-tools/flipr[flipr] R package installed before running the transition extractor.

The https://github.com/lifs-tools/flipr-trainer[flipr-trainer] project shows how to use the transition extractor.

// == References

// This project provides an execution harness for https://github.com/lifs-tools/flipr[flipR].

//  * **https://pubs.acs.org/doi/10.1021/acs.analchem.8b04310[N. Hoffmann et al., Analytical Chemistry 2019; Jan;91(5):3302-3310.] https://pubs.acs.org/doi/pdf/10.1021/acs.analchem.8b04310[PDF File.] https://www.ncbi.nlm.nih.gov/pubmed/30688441[PubMed record].**

